services:
  - type: web
    name: ezy-pay-bank-webhook
    env: node
    buildCommand: npm install && cd apps/bank-webhook && npm run build
    startCommand: cd apps/bank-webhook && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3003
